name: Check compatibility

on:
  push

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Check compatilibility
        env:
          GRGIT_USER: ${{ SECRETS.TOKEN }}
        run: ./gradlew checkCompatibility
      - name: check remote
        run: git remote -v
